/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://td47d4nwsfgproepm4o7ssvypi.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-tq6y6jahvzgn5bcsvdz6lrx4uu",
    "aws_cognito_identity_pool_id": "us-east-1:daa1783b-6c23-4b29-91f1-c51effb149c1",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_tJkcCejSn",
    "aws_user_pools_web_client_id": "4jev2nkv7lh14jguuimcgioq11",
    "oauth": {
        "domain": "mobileapp97cfcf35-97cfcf35-dev.auth.us-east-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "myapp://",
        "redirectSignOut": "myapp://",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_AND_IDENTITY_POOLS",
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [
        "FACEBOOK"
    ],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "mobileapp630d164c6686415b883d58bdf7a1d4f0210230-dev",
    "aws_user_files_s3_bucket_region": "us-east-1",
    "AWSS3": {
        "bucket": "shvaas-user-feed",
        "region": "us-west-2"
    }
};


export default awsmobile;
